from datetime import datetime
from typing import Annotated


class AgentContext:
    """Context object that holds shared state between agents."""

    # Core context information
    company_of_interest: Annotated[str, "Company that we are interested in trading"] = ""
    trade_date: Annotated[str, "What date we are trading at"] = ""


    # research step
    market_report: Annotated[str, "Report from the Market Analyst"] = ""
    sentiment_report: Annotated[str, "Report from the Social Media Analyst"] = ""
    news_report: Annotated[
        str, "Report from the News Researcher of current world affairs"
    ] = ""
    fundamentals_report: Annotated[str, "Report from the Fundamentals Analyst"] = ""

    equity_report: Annotated[str, "Report from the Equity Analyst"] = ""

    # researcher team discussion step
    investment_plan: Annotated[str, "Plan generated by the Analyst"] = ""

    trader_investment_plan: Annotated[str, "Plan generated by the Trader"] = ""

    # risk management team discussion step
    final_trade_decision: Annotated[str, "Final decision made by the Risk Analysts"] = ""

    def __init__(self):
        """Initialize AgentContext with default values."""
        self.trade_date = datetime.now().strftime("%Y-%m-%d")

    def generate_research_reports_md(self) -> str:
        """Generate markdown formatted research reports section."""
        return f"""## 市场研究报告
{self.market_report}

## 社交媒体情绪报告
{self.sentiment_report}

## 最新世界事务新闻
{self.news_report}

## 公司基本面报告
{self.fundamentals_report}

## 股票估值报告
{self.equity_report}"""

    def generate_all_reports_md(self) -> str:
        """Generate markdown formatted all reports including investment plan."""
        return f"""## 研究经理决策
{self.investment_plan}

{self.generate_research_reports_md()}"""
