from datetime import datetime
from typing import Annotated


class AgentContext:
    """Context object that holds shared state between agents."""

    # Core context information
    company_of_interest: Annotated[str, "Company that we are interested in trading"] = ""
    trade_date: Annotated[str, "What date we are trading at"] = ""


    # Analyst step
    market_report: Annotated[str, "Report from the Market Analyst"] = ""
    sentiment_report: Annotated[str, "Report from the Social Media Analyst"] = ""
    news_report: Annotated[str, "Report from the News Analyst"] = ""
    fundamentals_report: Annotated[str, "Report from the Fundamentals Analyst"] = ""
    equity_report: Annotated[str, "Report from the Equity Analyst"] = ""

    # Researcher team discussion step
    researcher_investment_plan: Annotated[str, "Plan generated by the researcher manager"] = ""

    trader_investment_plan: Annotated[str, "Plan generated by the Trader"] = ""

    # risk management team discussion step
    final_trade_decision: Annotated[str, "Final decision made by the Risk Analysts"] = ""

    def __init__(self):
        """Initialize AgentContext with default values."""
        self.trade_date = datetime.now().strftime("%Y-%m-%d")

    def generate_analyst_reports_md(self) -> str:
        """Generate markdown formatted research reports section."""
        return f"""## 股票技术面分析报告
{self.market_report}

## 股票社交媒体情绪面分析报告
{self.sentiment_report}

## 股票消息面分析报告
{self.news_report}

## 股票基本面分析报告
{self.fundamentals_report}

## 股票综合分析报告
{self.equity_report}"""

    def generate_trader_context_md(self) -> str:
        """Generate markdown formatted context for trader"""
        return f"""## 研究经理投资建议
{self.researcher_investment_plan}

{self.generate_analyst_reports_md()}"""


    def generate_risk_evaluation_context_md(self) -> str:
        """Generate markdown formatted context for risk evaluation"""
        return f"""## 交易员操作计划
{self.trader_investment_plan}

{self.generate_trader_context_md()}"""
