import os
import re
from datetime import datetime
from typing import Annotated, Dict, Optional

from agentscope.formatter import OpenAIChatFormatter, OpenAIMultiAgentFormatter
from agentscope.model import OpenAIChatModel

from tradingscope.default_config import DEFAULT_CONFIG


class AgentContext:
    """Context object that holds shared state between agents."""

    # Core context information
    company_of_interest: Annotated[str, "Company that we are interested in trading"] = ""
    trade_date: Annotated[str, "What date we are trading at"] = ""

    # Analyst step
    market_report: Annotated[str, "Report from the Market Analyst"] = ""
    sentiment_report: Annotated[str, "Report from the Social Media Analyst"] = ""
    news_report: Annotated[str, "Report from the News Analyst"] = ""
    fundamentals_report: Annotated[str, "Report from the Fundamentals Analyst"] = ""
    equity_report: Annotated[str, "Report from the Equity Analyst"] = ""

    # Researcher team discussion step
    researcher_investment_plan: Annotated[str, "Plan generated by the researcher manager"] = ""

    trader_investment_plan: Annotated[str, "Plan generated by the Trader"] = ""

    # risk management team discussion step
    final_trade_decision: Annotated[str, "Final decision made by the Risk Analysts"] = ""

    def __init__(self):
        """Initialize AgentContext with default values."""
        self.trade_date = datetime.now().strftime("%Y-%m-%d")

        # Model initialization
        self.model = OpenAIChatModel(
            model_name=DEFAULT_CONFIG["deep_think_llm"],
            api_key=os.environ.get("DASHSCOPE_API_KEY"),
            stream=True,
            generate_kwargs={"temperature": 0, "extra_body": {"enable_thinking": False}},
            client_kwargs={
                "max_retries": 2,
                "timeout": 120,
            },
        )

        # Formatter initialization
        self.chat_formatter = OpenAIChatFormatter()
        self.multi_agent_formatter = OpenAIMultiAgentFormatter()

    def generate_analyst_reports_md(self) -> str:
        """Generate markdown formatted research reports section."""
        sections = []

        if self.market_report:
            sections.append(f"## 股票技术面分析报告\n\n{self.market_report}")

        if self.sentiment_report:
            sections.append(f"## 股票社交媒体情绪面分析报告\n\n{self.sentiment_report}")

        if self.news_report:
            sections.append(f"## 股票消息面分析报告\n\n{self.news_report}")

        if self.fundamentals_report:
            sections.append(f"## 股票基本面分析报告\n\n{self.fundamentals_report}")

        return "\n\n---\n\n".join(sections)

    def generate_trader_context_md(self) -> str:
        """Generate markdown formatted context for trader"""
        return f"""## 研究经理投资建议

{self.researcher_investment_plan}

---

{self.generate_analyst_reports_md()}"""

    def generate_risk_evaluation_context_md(self) -> str:
        """Generate markdown formatted context for risk evaluation"""
        return f"""## 交易员操作计划

{self.trader_investment_plan}

---

{self.generate_trader_context_md()}"""

    def generate_full_report_md(self) -> str:
        """Generate the complete analysis report in markdown format.

        Returns:
            Complete markdown report with all sections properly formatted
        """
        sections = [f"# 股票分析报告: {self.company_of_interest} ({self.trade_date})"]

        if self.final_trade_decision:
            sections.append(f"## 最终交易决策\n\n{self.final_trade_decision}")

        if self.trader_investment_plan:
            sections.append(f"## 交易员操作计划\n\n{self.trader_investment_plan}")

        if self.researcher_investment_plan:
            sections.append(f"## 研究经理投资建议\n\n{self.researcher_investment_plan}")

        sections.append(self.generate_analyst_reports_md())

        return "\n\n---\n\n".join(sections)

    def generate_situation_summary(self) -> str:
        """Generate a condensed market situation summary for memory retrieval.

        This method creates a concise description of the current market situation
        from all analyst reports, optimized for semantic similarity search in
        the memory system.

        Returns:
            Condensed situation summary string
        """
        summary_parts = [
            f"股票: {self.company_of_interest}",
            f"日期: {self.trade_date}",
        ]

        # Extract key points from each report (first 500 chars as summary)
        if self.market_report:
            market_summary = self.market_report[:500].strip()
            summary_parts.append(f"市场技术面: {market_summary}")

        if self.fundamentals_report:
            fundamentals_summary = self.fundamentals_report[:500].strip()
            summary_parts.append(f"基本面: {fundamentals_summary}")

        if self.news_report:
            news_summary = self.news_report[:500].strip()
            summary_parts.append(f"消息面: {news_summary}")

        if self.sentiment_report:
            sentiment_summary = self.sentiment_report[:500].strip()
            summary_parts.append(f"情绪面: {sentiment_summary}")

        return "\n".join(summary_parts)

    def extract_prediction_data(self) -> Dict[str, Optional[str]]:
        """Extract structured prediction data from final trade decision.

        Parses the final_trade_decision text to extract:
        - direction: bullish/bearish/neutral
        - action: buy/sell/hold
        - confidence: 0-1 (from 置信度 field)
        - entry_price: suggested entry price
        - target_price: price target
        - stop_loss: stop loss price
        - reasoning: core reasoning (compressed)

        Returns:
            Dictionary with extracted prediction fields
        """
        result = {
            "direction": "neutral",
            "action": "hold",
            "confidence": 0.5,
            "entry_price": None,
            "target_price": None,
            "stop_loss": None,
            "reasoning": "",
        }

        decision_text = self.final_trade_decision
        if not decision_text:
            decision_text = self.trader_investment_plan

        if not decision_text:
            return result

        text_lower = decision_text.lower()

        # Extract action (buy/sell/hold)
        if any(kw in text_lower for kw in ["买入", "buy", "做多", "增持"]):
            result["action"] = "buy"
            result["direction"] = "bullish"
        elif any(kw in text_lower for kw in ["卖出", "sell", "做空", "减持", "清仓"]):
            result["action"] = "sell"
            result["direction"] = "bearish"
        else:
            result["action"] = "hold"
            result["direction"] = "neutral"

        # Extract confidence (置信度)
        confidence_patterns = [
            r"置信度[：:]\s*(\d+\.?\d*)",
            r"信心[：:]\s*(\d+\.?\d*)",
            r"confidence[：:]\s*(\d+\.?\d*)",
        ]
        for pattern in confidence_patterns:
            match = re.search(pattern, decision_text, re.IGNORECASE)
            if match:
                conf = float(match.group(1))
                # Normalize to 0-1 if given as percentage
                if conf > 1:
                    conf = conf / 100
                result["confidence"] = min(1.0, max(0.0, conf))
                break

        # Extract entry price
        entry_patterns = [
            r"入场价[：:位]\s*\$?(\d+\.?\d*)",
            r"建议入场[：:价]\s*\$?(\d+\.?\d*)",
            r"entry[：:\s]+\$?(\d+\.?\d*)",
        ]
        for pattern in entry_patterns:
            match = re.search(pattern, decision_text, re.IGNORECASE)
            if match:
                result["entry_price"] = float(match.group(1))
                break

        # Extract target price
        target_patterns = [
            r"目标价[：:位]\s*\$?(\d+\.?\d*)",
            r"目标[：:\s]+\$?(\d+\.?\d*)",
            r"target[：:\s]+\$?(\d+\.?\d*)",
        ]
        for pattern in target_patterns:
            match = re.search(pattern, decision_text, re.IGNORECASE)
            if match:
                result["target_price"] = float(match.group(1))
                break

        # Extract stop loss
        stop_patterns = [
            r"止损[价位：:]\s*\$?(\d+\.?\d*)",
            r"stop.?loss[：:\s]+\$?(\d+\.?\d*)",
        ]
        for pattern in stop_patterns:
            match = re.search(pattern, decision_text, re.IGNORECASE)
            if match:
                result["stop_loss"] = float(match.group(1))
                break

        # Extract reasoning (first meaningful paragraph)
        reasoning_parts = []

        # Look for key decision points
        reason_patterns = [
            r"决策理由[：:](.*?)(?:\n\n|\n#|$)",
            r"核心逻辑[：:](.*?)(?:\n\n|\n#|$)",
            r"主要原因[：:](.*?)(?:\n\n|\n#|$)",
        ]
        for pattern in reason_patterns:
            match = re.search(pattern, decision_text, re.DOTALL)
            if match:
                reasoning_parts.append(match.group(1).strip()[:100])
                break

        # If no explicit reasoning, extract from action context
        if not reasoning_parts:
            # Find sentences containing the action keyword
            sentences = re.split(r"[。\.\n]", decision_text)
            action_keywords = ["买入", "卖出", "持有", "buy", "sell", "hold"]
            for sent in sentences:
                if any(kw in sent.lower() for kw in action_keywords) and len(sent) > 20:
                    reasoning_parts.append(sent.strip()[:100])
                    break

        result["reasoning"] = "".join(reasoning_parts)[:100] if reasoning_parts else "未提供详细理由"

        return result
